XYK\PMP\EntityBundle\Entity\ExamType:
    type: entity
    table: exam_type
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: false
            length: 150
            fixed: false
            comment: ''
        description:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        totalQuestions:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
        groupQuestions:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            column: group_questions
        areaQuestions:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            column: area_questions
        current:
            type: datetime
            nullable: false
            comment: ''
        groupName:
            type: string
            nullable: false
            length: 150
            fixed: false
            comment: ''
            column: group_name
        areaName:
            type: string
            nullable: false
            length: 150
            fixed: false
            comment: ''
            column: area_name
        examMinutes:
            type: integer
            nullable: false
            column: exam_minutes
        groupMinutes:
            type: integer
            nullable: false
            column: group_minutes
        subGroup:
            type: boolean
            nullable: true
            column: sub_group
            
            
    
    lifecycleCallbacks: {  }