XYK\PMP\EntityBundle\Entity\ExamQuestion:
    type: entity
    table: exam_question
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        order:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: order_question
            
        solved:
            type: boolean
            nullable: true
            comment: ''
        current:
            type: datetime
            nullable: false
            comment: ''
    manyToOne:
        exam:
            targetEntity: Exam
            cascade: ["persist"]
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_exam:
                    referencedColumnName: id
            orphanRemoval: false
        question:
            targetEntity: Question
            cascade: ["persist"]
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_question:
                    referencedColumnName: id
            orphanRemoval: false
        answer:
            targetEntity: Answer
            cascade: ["persist"]
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_answer:
                    referencedColumnName: id
            orphanRemoval: false
            
        
    lifecycleCallbacks: {  }