XYK\PMP\EntityBundle\Entity\Exam:
    type: entity
    table: exam
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        timer:
            type: bigint
            nullable: false
        finished:
            type: boolean
            nullable: false
            comment: ''
        percentage:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            default: '0::real'
        group:
            type: boolean
            nullable: false
            comment: ''
            column: group_exam
        area:
            type: boolean
            nullable: false
            comment: ''
            column: area_exam
        name:
            type: string
            nullable: true
            length: 150
            fixed: false
            comment: ''
        current:
            type: datetime
            nullable: false
            comment: ''
    manyToOne:
        examType:
            targetEntity: ExamType
            cascade: ["persist"]
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_exam_type:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            cascade: ["persist"]
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_user:
                    referencedColumnName: id
            orphanRemoval: false
            
        
    lifecycleCallbacks: {  }