XYK\PMP\EntityBundle\Entity\KnowledgeArea:
    type: entity
    repositoryClass: XYK\PMP\EntityBundle\Repository\KnowledgeAreaRepository
    table: konwledge_area
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: false
            length: 150
            fixed: false
            comment: ''
        description:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        percentage:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        current:
            type: datetime
            nullable: false
            comment: ''
    manyToOne:
        examType:
            targetEntity: ExamType
            cascade: ["persist"]
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_exam_type:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
