XYK\PMP\EntityBundle\Entity\KnowledgeArea:
    type: entity
    table: konwledge_area
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: false
            length: 150
            fixed: false
            comment: ''
        description:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        percentage:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        current:
            type: datetime
            nullable: false
            comment: ''
    lifecycleCallbacks: {  }
