XYK\PMP\EntityBundle\Entity\Question:
    type: entity
    table: question
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        title:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        explanation:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        current:
            type: datetime
            nullable: false
            comment: ''
    manyToOne:
        examType:
            targetEntity: ExamType
            cascade: ["persist"]
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_exam_type:
                    referencedColumnName: id
            orphanRemoval: false
        knowledgeArea:
            targetEntity: KnowledgeArea
            cascade: ["persist"]
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_knowledge_area:
                    referencedColumnName: id
            orphanRemoval: false
        proccessGroup:
            targetEntity: ProccessGroup
            cascade: ["persist"]
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_proccess_group:
                    referencedColumnName: id
            orphanRemoval: false     
    oneToMany:
        answers:
            targetEntity: Answer
            mappedBy: question
            cascade: ["persist"]
        
    lifecycleCallbacks: {  }
