## YAML Template.
---
fos_user:
  #  from_email:
  #      address:        noreply@example.com
  #      sender_name:    Demo App
    registration:
        
        confirmation:
            enabled: true
 #   resetting:
 #       email:
 #           from_email:
 #               address:        resetting@example.com
 #               sender_name:    Demo Resetting
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Entity\User
 
    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager
 
    service:
        user_manager: sonata.user.orm.user_manager
 
    profile:
        # Authentication Form
        form:
            type:               fos_user_profile
            handler:            fos_user.profile.form.handler.default
            name:               fos_user_profile_form
            validation_groups:  [Authentication]