homepage:
    pattern:  /
    defaults: { _controller: MainBundle:Default:index }

question:
    path:     /question/{id}/{idExam}
    defaults: { _controller: MainBundle:Exam:question, idExam: null,  }

exam:
    path:   /exam/{idExam}/{idGroup}/{idType}/{idExamType}
    defaults: { _controller: MainBundle:Exam:generateExam,idExam: -1, idExamType: 1, idType: -1, idGroup: -1 }

solveQuestion:
    path:   /solve
    defaults: { _controller: MainBundle:Exam:solveQuestion }
    
finishExam:
    path: /finish
    defaults: { _controller: MainBundle:Exam:finishExam }
    
history:
    path: /history
    defaults: { _controller: MainBundle:Exam:history }
    
search:
    path: /search
    defaults: { _controller: MainBundle:Exam:search}
    
searchQuestion:
    path: /searchQuestion
    defaults: { _controller: MainBundle:Exam:searchQuestion}
    
searchArea:
    path: /area
    defaults: { _controller: MainBundle:Exam:area}
    
areaExam:
    path: /areaExam
    defaults: { _controller: MainBundle:Exam:areaExam}
    
report:
    path: /getReport/{idExam}
    defaults: { _controller: MainBundle:Exam:report  }
    