question:
    path:     /question/{id}/{idExam}
    defaults: { _controller: MainBundle:Exam:question, idExam: null,  }

exam:
    path:   /exam/{idExam}/{idGroup}/{idType}/{idExamType}
    defaults: { _controller: MainBundle:Exam:generateExam,idExam: -1, idExamType: 1, idType: -1, idGroup: -1 }

solveQuestion:
    path:   /solve
    defaults: { _controller: MainBundle:Exam:solveQuestion }
    
finishExam:
    path: /finish
    defaults: { _controller: MainBundle:Exam:finishExam }